# Generated by Django 3.2.7 on 2021-09-11 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='author',
            options={'ordering': ('-birthYear',)},
        ),
        migrations.AlterModelOptions(
            name='book',
            options={'ordering': ('name',)},
        ),
        migrations.AlterModelOptions(
            name='theme',
            options={'ordering': ('-name',)},
        ),
        migrations.AddField(
            model_name='book',
            name='publishTime',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
