# Generated by Django 3.2.7 on 2021-09-11 02:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0002_auto_20210910_2325'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'ordering': ('-publishTime',)},
        ),
        migrations.RemoveField(
            model_name='book',
            name='year',
        ),
    ]
