# Generated by Django 3.2.7 on 2021-09-11 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0003_auto_20210910_2338'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='synopsis',
            field=models.TextField(default='asdasdasdada'),
            preserve_default=False,
        ),
    ]
