# Generated by Django 3.2.7 on 2021-09-11 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0004_book_synopsis'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='publishTime',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
