# Generated by Django 3.2.7 on 2021-09-12 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0006_article'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Article',
        ),
    ]
