# Generated by Django 3.2.7 on 2021-09-12 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0007_delete_article'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='pageQuant',
            field=models.IntegerField(default=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='theme',
            name='books',
            field=models.IntegerField(default=1123),
            preserve_default=False,
        ),
    ]
