# Generated by Django 3.2.7 on 2021-09-12 20:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0008_auto_20210912_1732'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='pageQuant',
        ),
    ]
